### ISSUE TITLE
Compiler warnings about the visibility attribute from mingw

### ISSUE THREAD

**Issue by nemequ** [google/brotli#352]
When attempting to cross-compile with mingw, I see a lot of "error: visibility attribute not supported in this configuration; ignored [-Werror=attributes]" messages (normally they're just warnings, but I use -Werror for CI builds).  See https://travis-ci.org/quixdb/squash/jobs/132697469#L1320 for an example.  I can reproduce on Fedora with Squash with something like `ming64-cmake . && make -j`.

If you want, you can adapt https://github.com/quixdb/squash/blob/26aa037b618c1a37d984099b8dd5a3e04d3058c3/squash/squash.h#L115

**Comment by eustas** [comment]
Thanks. We're going to adapt it in few steps: first resolve the compiler warnings and later, when we are ready for windows, grab __declspec part.

**Comment by eustas** [comment]
Should be fixed.

**Comment by nemequ** [comment]
Looks like it's still an issue: https://travis-ci.org/quixdb/squash/jobs/136512277

That's with 09543b5fc5637f1cda7a54dbf2b17f892006891b (you can verify that at https://travis-ci.org/quixdb/squash/jobs/136512277#L198).

On a somewhat related note (an easy way to switch compilers), if you are interested I'd be willing to put together a CMake-based build system for you; it could be useful for Squash, too, since we could share the build system…

**Comment by eustas** [comment]
Ooops, thought it was about unused function...
Visibility is fixed in v0.4, going to back-port fix soon.

**Comment by eustas** [comment]
Should be fixed. _Déjà vu?_

**Comment by nemequ** [comment]
Thanks, it works :)

https://travis-ci.org/quixdb/squash/builds/137077283
